build-cqlQueryFunction:
	
	yarn
	
	
	
	cp -R node_modules $(ARTIFACTS_DIR)
	cp cql-app.js $(ARTIFACTS_DIR)
	cp FHIRHelpers.json $(ARTIFACTS_DIR)
	cp conjunctivitis-detection-elm.json $(ARTIFACTS_DIR)
	cp yarn.lock $(ARTIFACTS_DIR)
	
    